markets:

  nhl:

    moneyline:
      enabled: true
      pick_preference: best_ev

      home:
        enabled: true
        odds_bands:
          - [-150, -1]
          - [0, 250]
        ev_min: 0.05
        ev_max: 0.05
        kelly_min: 0.00
        kelly_max: 0.05

      away:
        enabled: true
        odds_bands:
          - [-250, -1]
          - [0, 250]
        ev_min: 0.00
        ev_max: 0.05
        kelly_min: 0.00
        kelly_max: 0.05

    puck_line:
      enabled: true
      pick_preference: best_ev

      home:
        enabled: true
        line_bands:
          - [1.5, 1.5]
        odds_bands:
          - [-300, 150]
        ev_min: 0.00
        ev_max: 0.10
        kelly_min: 0.0
        kelly_max: 1.0

      away:
        enabled: true
        line_bands:
          - [1.5, 1.5]
          - [-1.5, -1.5]
        odds_bands:
          - [-300, -0.1]
          - [0, 999]
        ev_min: 0.00
        ev_max: 0.10
        kelly_min: 0.0
        kelly_max: 1.0

    total:
      enabled: true
      pick_preference: best_ev

      over:
        enabled: true
        line_bands:
          - [4.5, 7.5]
        ev_min: 0.00
        ev_max: 0.10
        kelly_min: 0.00
        kelly_max: 0.1

      under:
        enabled: true
        line_bands:
          - [4.5, 7.5]
        ev_min: 0.00
        ev_max: 0.10
        kelly_min: 0.00
        kelly_max: 0.1
