name: Generate O/U Band Analysis

on:
  workflow_dispatch:

jobs:
  generate-ou-bands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run O/U band analysis
        run: |
          python scripts/zou_bands.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add bets/historic/totals/*.csv

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update O/U totals band analysis"
            git push
          fi
