markets:

###################################################################################################
# NBA CONFIG ######################################################################################
###################################################################################################

  nba:

    moneyline:
      enabled: true
      pick_preference: best_ev

#################################################################
## HOME NBA MONEYLINE ###########################################
#################################################################
      home:
        enabled: true
        odds_bands:
          - [-500, -175]
          - [175, 200]
        ev_min: 0.005
        ev_max: 0.10
        kelly_min: 0.005
        kelly_max: 0.1

#################################################################
## AWAY NBA MONEYLINE ###########################################
#################################################################
      away:
        enabled: true
        odds_bands:
          - [-500, -175]
        ev_min: 0.005
        ev_max: 0.10
        kelly_min: 0.01
        kelly_max: 0.1

#################################################################
## NBA SPREAD ###################################################
#################################################################

    spread:
      enabled: true
      pick_preference: best_ev

#################################################################
## HOME NBA SPREAD ##############################################
#################################################################
      home:
        enabled: true
        line_bands:
          - [-8.5, -3.5]

        ev_min: 0.045
        ev_max: 0.18
        kelly_min: 0.015
        kelly_max: 0.08

#################################################################
## AWAY NBA SPREAD ##############################################
#################################################################
      away:
        enabled: true
        line_bands:
          - [3.5, 9.5]

        ev_min: 0.065
        ev_max: 0.20
        kelly_min: 0.015
        kelly_max: 0.08

#################################################################
## NBA TOTAL ####################################################
#################################################################

    total:
      enabled: true
      pick_preference: best_ev

#################################################################
## OVER NBA TOTAL ###############################################
#################################################################
      over:
        enabled: true
        line_bands:
          - [225, 237]
        ev_min: 0.01
        ev_max: 0.10
        kelly_min: 0.01
        kelly_max: 0.1

#################################################################
## UNDER NBA TOTAL ##############################################
#################################################################
      under:
        enabled: true
        line_bands:
          - [215, 225]
          - [240, 248]
        ev_min: 0.02
        ev_max: 0.10
        kelly_min: 0.01
        kelly_max: 0.07

###################################################################################################
# NCAAB CONFIG ####################################################################################
###################################################################################################

  ncaab:

    moneyline:
      enabled: true
      pick_preference: best_ev

#################################################################
## HOME NCAAB MONEYLINE #########################################
#################################################################
      home:
        enabled: true
        odds_bands:
          - [-500, -200]
          - [-130, -109]
          - [110, 150]
        ev_min: 0.002
        ev_max: 0.063
        kelly_min: 0.001
        kelly_max: 0.1

#################################################################
## AWAY NCAAB MONEYLINE #########################################
#################################################################
      away:
        enabled: true
        odds_bands:
          - [-150, -109]
          - [101, 130]
        ev_min: 0.007
        ev_max: 0.06
        kelly_min: 0.001
        kelly_max: 0.1

#################################################################
## NCAAB SPREAD #################################################
#################################################################

    spread:
      enabled: true
      pick_preference: best_ev

#################################################################
## HOME NCAAB SPREAD ############################################
#################################################################
      home:
        enabled: true
        line_bands:
          - [-8.5, -3.5]

        ev_min: 0.045
        ev_max: 0.18
        kelly_min: 0.015
        kelly_max: 0.50

#################################################################
## AWAY NCAAB SPREAD ############################################
#################################################################
      away:
        enabled: true
        line_bands:
          - [3.5, 9.5]

        ev_min: 0.065
        ev_max: 0.20
        kelly_min: 0.015
        kelly_max: 0.50

#################################################################
## NCAAB TOTAL ##################################################
#################################################################

    total:
      enabled: true
      pick_preference: best_ev

#################################################################
## OVER NCAAB TOTAL #############################################
#################################################################
      over:
        enabled: true
        line_bands:
          - [156, 250]
        ev_min: 0.02
        ev_max: 0.10
        kelly_min: 0.001
        kelly_max: 0.1

#################################################################
## UNDER NCAAB TOTAL ############################################
#################################################################
      under:
        enabled: true
        line_bands:
          - [130, 139.9]
          - [150, 155]
        ev_min: 0.03
        ev_max: 0.04
        kelly_min: 0.001
        kelly_max: 0.1
