markets:

  mlb:

    moneyline:
      enabled: true
      pick_preference: best_ev

      home:
        enabled: true
        odds_bands:
          - [-200, -1]
          - [0, 200]
        ev_min: 0.001
        ev_max: 0.99
        kelly_min: 0.01
        kelly_max: 0.99

      away:
        enabled: true
        odds_bands:
          - [-200, -1]
          - [0, 200]
        ev_min: 0.001
        ev_max: 0.99
        kelly_min: 0.01
        kelly_max: 0.99

    run_line:
      enabled: true
      pick_preference: best_ev

      home:
        enabled: true
        line_bands:
          - [-1.5, -0.5]
        odds_bands:
          - [-200, 200]
        ev_min: 0.001
        ev_max: 0.99
        kelly_min: 0.01
        kelly_max: 0.99

      away:
        enabled: true
        line_bands:
          - [-1.5, -0.5]
        odds_bands:
          - [-200, 200]
        ev_min: 0.001
        ev_max: 0.99
        kelly_min: 0.01
        kelly_max: 0.99

    total:
      enabled: true
      pick_preference: best_ev

      over:
        enabled: true
        line_bands:
          - [6.0, 18.0]
        odds_bands:
          - [-250, 100]
        ev_min: 0.001
        ev_max: 0.99
        kelly_min: 0.01
        kelly_max: 0.99

      under:
        enabled: true
        line_bands:
          - [6.0, 18.0]
        odds_bands:
          - [-250, -110]
        ev_min: 0.001
        ev_max: 0.99
        kelly_min: 0.01
        kelly_max: 0.99
