markets:

  mlb:
###################################################
    moneyline:
      enabled: true
      pick_preference: best_ev

      home:
        enabled: true
        odds_bands:
          - [-500, 500]
        ev_bands:
          - [0.00, 0.99]
        kelly_bands:
          - [0.00, 0.99]
        prob_min: 0.20

###################################################
      away:
        enabled: true
        odds_bands:
          - [-500, 500]
        ev_bands:
          - [0.00, 0.99]
        kelly_bands:
          - [0.00, 0.99]
        prob_min: 0.20

###################################################
    run_line:
      enabled: true
      pick_preference: best_prob

      home:
        enabled: true
        line_bands:
          - [-1.5, 1.5]
        odds_bands:
          - [-500, 500]
        ev_bands:
          - [0.00, 0.99]
        kelly_bands:
          - [0.00, 0.99]
        prob_min: 0.20

      away:
        enabled: true
        line_bands:
          - [-1.5, 1.5]
        odds_bands:
          - [-500, 500]
        ev_bands:
          - [0.00, 0.99]
        kelly_bands:
          - [0.00, 0.99]
        prob_min: 0.20

###################################################
    total:
      enabled: true
      pick_preference: best_ev

      over:
        enabled: true
        line_bands:
          - [0.0, 19.0]
        odds_bands:
          - [-500, 500]
        ev_bands:
          - [0.00, 0.99]
        kelly_bands:
          - [0.00, 0.99]

###################################################
      under:
        enabled: true
        line_bands:
          - [0.0, 19.0]
        odds_bands:
          - [-500, 500]
        ev_bands:
          - [0.00, 0.99]
        kelly_bands:
          - [0.00, 0.99]
