markets:
  soccer:

    match_odds:
      home:
        enabled: true
        ev_min: 0.00
        ev_max: 0.999
        kelly_min: 0.00
        kelly_max: 0.999
        odds_bands:
          - [1.5, 3.5]

      draw:
        enabled: true
        ev_min: 0.00
        ev_max: 0.999
        kelly_min: 0.00
        kelly_max: 0.999
        odds_bands:
          - [2.5, 5.5]

      away:
        enabled: true
        ev_min: 0.0
        ev_max: 0.999
        kelly_min: 0.00
        kelly_max: 0.999
        odds_bands:
          - [1.8, 6.0]

    totals:
      over:
        enabled: true
        ev_min: 0.03
        ev_max: 0.50
        kelly_min: 0.01
        kelly_max: 0.30

      under:
        enabled: true
        ev_min: 0.00
        ev_max: 0.999
        kelly_min: 0.00
        kelly_max: 0.999

    btts:
      "yes":
        enabled: true
        ev_min: 0.00
        ev_max: 0.999
        kelly_min: 0.00
        kelly_max: 0.999

      "no":
        enabled: true
        ev_min: 0.00
        ev_max: 0.999
        kelly_min: 0.00
        kelly_max: 0.999
