markets:

  epl:
    result:
      min_edge: 0.00001
    total:
      min_edge: 0.00001
    btts:
      min_edge: 0.00001
      min_edge_from_50: 0.05

  laliga:
    result:
      min_edge: 0.00001
    total:
      min_edge: 0.00001
    btts:
      min_edge: 0.00001
      min_edge_from_50: 0.05

  bundesliga:
    result:
      min_edge: 0.00001
    total:
      min_edge: 0.00001
    btts:
      min_edge: 0.00001
      min_edge_from_50: 0.05

  seriea:
    result:
      min_edge: 0.00001
    total:
      min_edge: 0.00001
    btts:
      min_edge: 0.00001
      min_edge_from_50: 0.05

  ligue1:
    result:
      min_edge: 0.00001
    total:
      min_edge: 0.00001
    btts:
      min_edge: 0.00001
      min_edge_from_50: 0.05

  mls:
    result:
      min_edge: 0.00001
    total:
      min_edge: 0.00001
    btts:
      min_edge: 0.00001
      min_edge_from_50: 0.05
