name: 00 Odds API Pull

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python scripts/odds_api.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add docs/win/basketball/odds/*
          git add docs/win/hockey/odds/*
          git add docs/win/baseball/odds/*
          

          git commit -m "Update odds data" || echo "No changes to commit"
          git push
