name: Qodana

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  qodana:
    name: Qodana - bet_tracker
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2026.2
        with:
          args: |
            --image jetbrains/qodana-python:2026.2
            --config qodana.yaml
          pr-mode: false
          push-fixes: none
          artifact-name: qodana-bet-tracker
          primary-cache-key: qodana-2026.2-bet-tracker-docker-stable-v1-${{ github.ref }}-${{ github.sha }}
          additional-cache-key: qodana-2026.2-bet-tracker-docker-stable-v1-${{ github.ref }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1493839823 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
          QODANA_PYTHON_PATH: '/data/cache/conda/envs/bet_tracker_py314/bin/python'
