name: Run Data Merge

on:
  workflow_dispatch: 

jobs:
  run-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install pandas

      - name: Run merge script
        run: python scripts/merge_edges_files.py

        env:
          # ============================================
          # UPDATE THESE 2 VALUES + GIT ADD BELOW
          # ============================================
          INPUT_FOLDER: docs/win/basketball/03_edges
          OUTPUT_FILE: docs/win/basketball/03_edges/merged
         

      - name: Commit merged output to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          # ============================================
          # UPDATE GIT ADD BELOW
          # ============================================
          git add docs/win/basketball/03_edges/merged/
          git commit -m "Automated merge output update" || echo "No changes to commit"
          git push
